[project]
name = "call-me-maybe"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "llm-sdk",
    "pydantic>=2.13.4",
    "regex>=2026.7.19",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.3.1",
    "types-regex>=2026.7.19.20260720",
]

[tool.uv.workspace]
members = [
    "llm_sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true, editable = true }

[[tool.mypy.overrides]]
module = "llm_sdk.*"
follow_imports = "skip"
